### PR TITLE
Code readability and error/warning/verbose info fixes

### PR DESCRIPTION
**Pull request by MisterZeus**

### CODE REVIEW

**Comment by asheroto** [comment]
Some of the changes look good, but many sources discourage and even recommend avoiding the use of `Write-Host`. What are your thoughts on that?

https://www.google.com/search?hl=en&q=avoid%20using%20write%20host

**Comment by MisterZeus** [comment]
Good point, the reason I changed them to `Write-Host` was that when I was adding debug messages and showing variables to various functions, they ended up polluting the functions' output values.

e.g. the top comment on this answer mentions this problem too:
https://stackoverflow.com/a/19754384/1387817

I reckon a middle ground might be a good idea,
where the functions of your script use `Write-Host`,
then the "main" script uses `Write-Output`?

Or we can swap it all back to Write-Output if you prefer.
I could work around that by debugging with Write-Verbose, which is what it's used for usually.

Let me know what you reckon :-)

**Comment by MisterZeus** [comment]
I think I might have been polluting it myself accidentally while debugging. I swapped all the Write-Host stuff back to Write-Output and test run it on a different device, worked a treat!
Let me know if any other tweaks/cleanup needed.

**Comment by asheroto** [comment]
Thanks for your work on this, about to release an update.

**Pull request merged**
