### PR TITLE
Update README.md to add a one-liner command

### PR DESCRIPTION
**Pull request by gerardog**
Hi! Your script was exactly what I needed. It only lacked a fast, copy paste one-liner. So I added one.
I know some stranger editing your content without first asking is maybe rude or at least not easy to digest, so if you cancel this PR I won't get offended. Thanks for the script!

### CODE REVIEW

**Comment by asheroto** [comment]
Beautiful! thanks!

**Review by asheroto — COMMENTED** [review]
thanks again, sorry it was so delayed, some how I missed this

**Comment by asheroto** [comment]
Released a new version just now and mentioned you in the release notes, didn't incorporate the PR because of the major overhaul., although I did use some of your changes. Thank you though!

**Comment by gerardog** [comment]
Perfect! but you omitted this piece of info: 
- WinGet (and therefore this script) requires "Windows 10 version 1809 or newer (LTSC included)" 

This can be pretty useful, since people using this script probably is using an older windows 10 version.
I've personally used this script to test a WinGet package I was working on, in the 'oldest possible' (non-updated) Win10.

**Comment by asheroto** [comment]
Thanks. I had some issue with git locally on my end so some things didn't make it.

I've got it updated now.

**Pull request closed without merging**
